from .user import User as UserResource
from .user import Users as UsersResource
from .pedidos import Pedidos as PedidosResource
from .pedidos import Pedido as PedidoResource
from .valoraciones import Valoracion as ValoracionResource
from .valoraciones import Valoraciones as ValoracionesResource
from .notificaciones import Notificaciones as NotificacionResource
from .animal import Animal as AnimalResource
from .animal import Animales as AnimalesResource
from .notificacioness import Notificaciones as Notificaciones
from .valoracioness import Valoracion as Valoracion
from .valoracioness import Valoraciones as Valoraciones
